// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANFK5KB9fwCbMnmu5pfe2y0NSqoii0SDA',
    appId: '1:1032090541001:web:d5c7cf934a5864ecc7a618',
    messagingSenderId: '1032090541001',
    projectId: 'batch-notice-app',
    authDomain: 'batch-notice-app.firebaseapp.com',
    storageBucket: 'batch-notice-app.firebasestorage.app',
    measurementId: 'G-WWF02V1Z4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PR5PrEFUkjuCF4TvPoIqg36Jz4KhNkY',
    appId: '1:1032090541001:android:b852c756baf86d2dc7a618',
    messagingSenderId: '1032090541001',
    projectId: 'batch-notice-app',
    storageBucket: 'batch-notice-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3CwSV8MbOFS9gxcwNjD1aeMMjOY9kBfY',
    appId: '1:1032090541001:ios:1cae83759c37ed5bc7a618',
    messagingSenderId: '1032090541001',
    projectId: 'batch-notice-app',
    storageBucket: 'batch-notice-app.firebasestorage.app',
    iosBundleId: 'com.example.batchNoticeAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3CwSV8MbOFS9gxcwNjD1aeMMjOY9kBfY',
    appId: '1:1032090541001:ios:1cae83759c37ed5bc7a618',
    messagingSenderId: '1032090541001',
    projectId: 'batch-notice-app',
    storageBucket: 'batch-notice-app.firebasestorage.app',
    iosBundleId: 'com.example.batchNoticeAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANFK5KB9fwCbMnmu5pfe2y0NSqoii0SDA',
    appId: '1:1032090541001:web:efe6e46581201af5c7a618',
    messagingSenderId: '1032090541001',
    projectId: 'batch-notice-app',
    authDomain: 'batch-notice-app.firebaseapp.com',
    storageBucket: 'batch-notice-app.firebasestorage.app',
    measurementId: 'G-GH1628529Y',
  );

}