// lib/main.dart
// Infyners - Batch Notice App
// Single-file: Firebase Auth, Firestore (notices, exams, routines), local notifications
// Keep firebase_options.dart generated by `flutterfire configure` in the same folder.

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:fluttertoast/fluttertoast.dart';

import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;
import 'firebase_options.dart';

// -------------------- Notifications Setup --------------------
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

Future<void> initializeNotifications() async {
  // Initialize timezone data
  tz.initializeTimeZones();

  // Remove FlutterNativeTimezone usage
  // Set your local timezone manually or default to UTC
  tz.setLocalLocation(tz.getLocation('UTC')); // <- just UTC or your preferred timezone

  const AndroidInitializationSettings androidInit =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  const InitializationSettings initSettings = InitializationSettings(
    android: androidInit,
  );

  await flutterLocalNotificationsPlugin.initialize(initSettings);

  // Request permissions for iOS/macOS
  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
      ?.requestPermissions(alert: true, badge: true, sound: true);

  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<MacOSFlutterLocalNotificationsPlugin>()
      ?.requestPermissions(alert: true, badge: true, sound: true);
}


Future<void> showNotification(String title, String body) async {
  const AndroidNotificationDetails androidDetails = AndroidNotificationDetails(
    'infyners_channel',
    'Infyners Notifications',
    channelDescription: 'Notifications for Infyners app',
    importance: Importance.max,
    priority: Priority.high,
    showWhen: true,
  );

  const NotificationDetails platformDetails = NotificationDetails(android: androidDetails);

  await flutterLocalNotificationsPlugin.show(
    DateTime.now().millisecond,
    title,
    body,
    platformDetails,
    payload: null,
  );
}

// -------------------- Admin Helper --------------------
// Checks two places: /admins/{uid} and /users/{uid} role/isAdmin flag.
// Returns false on error or if not signed-in.
Future<bool> isCurrentUserAdmin() async {
  final user = FirebaseAuth.instance.currentUser;
  if (user == null) return false;
  final uid = user.uid;

  try {
    // Preferred: admins collection
    final adminDoc = await FirebaseFirestore.instance.collection('admins').doc(uid).get();
    if (adminDoc.exists) return true;

    // Fallback: users collection with role/isAdmin
    final userDoc = await FirebaseFirestore.instance.collection('users').doc(uid).get();
    if (userDoc.exists) {
      final data = userDoc.data()!;
      if (data['role'] == 'admin' || data['isAdmin'] == true) return true;
    }
  } catch (e) {
    debugPrint('Admin check error: $e');
  }
  return false;
}

// -------------------- Main --------------------
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await initializeNotifications();
  runApp(const InfynersApp());
}

class InfynersApp extends StatelessWidget {
  const InfynersApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Infyners',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        textTheme: GoogleFonts.poppinsTextTheme(),
        useMaterial3: true,
      ),
      home: const AuthGate(),
    );
  }
}

// -------------------- Auth Gate --------------------
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          // show splash/loading while checking auth state
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        if (snapshot.hasData) {
          return const HomePage();
        } else {
          return const LoginPage();
        }
      },
    );
  }
}

// -------------------- Login Page --------------------
class LoginPage extends StatefulWidget {
  const LoginPage({super.key});
  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final email = TextEditingController();
  final password = TextEditingController();
  bool _loading = false;

  Future<void> login() async {
    setState(() => _loading = true);
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: email.text.trim(),
        password: password.text.trim(),
      );
      Fluttertoast.showToast(msg: "Login successful!");
    } catch (e) {
      Fluttertoast.showToast(msg: "Login failed: ${e.toString()}");
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  void dispose() {
    email.dispose();
    password.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.indigo.shade50,
      body: Center(
        child: SingleChildScrollView(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            Card(
              elevation: 6,
              margin: const EdgeInsets.all(25),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
              child: Padding(
                padding: const EdgeInsets.all(25),
                child: Column(mainAxisSize: MainAxisSize.min, children: [
                  Text("Infyners Login",
                      style: GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w600)),
                  const SizedBox(height: 20),
                  TextField(controller: email, decoration: const InputDecoration(labelText: "Email")),
                  const SizedBox(height: 8),
                  TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: "Password")),
                  const SizedBox(height: 16),
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: _loading ? null : login,
                      style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, foregroundColor: Colors.white),
                      child: _loading ? const SizedBox(height: 18, width: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Text("Login"),
                    ),
                  ),
                ]),
              ),
            ),
            const SizedBox(height: 8),
            Text("Developed by Sagnik Saha Dibbay", style: GoogleFonts.poppins(fontSize: 12, color: Colors.black54)),
            const SizedBox(height: 14),
          ]),
        ),
      ),
    );
  }
}

// -------------------- Home Page --------------------
class HomePage extends StatefulWidget {
  const HomePage({super.key});
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int _index = 0;
  final pages = [const NoticePage(), const ExamPage(), const RoutinePage()];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Infyners'),
        backgroundColor: Colors.indigo,
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () async {
              await FirebaseAuth.instance.signOut();
            },
          )
        ],
      ),
      body: pages[_index],
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index,
        onDestinationSelected: (i) => setState(() => _index = i),
        destinations: const [
          NavigationDestination(icon: Icon(Icons.announcement), label: "Notices"),
          NavigationDestination(icon: Icon(Icons.assignment), label: "Exams"),
          NavigationDestination(icon: Icon(Icons.schedule), label: "Routine"),
        ],
      ),
    );
  }
}

// -------------------- Notice Page --------------------
class NoticePage extends StatefulWidget {
  const NoticePage({super.key});
  @override
  State<NoticePage> createState() => _NoticePageState();
}

class _NoticePageState extends State<NoticePage> {
  final notice = TextEditingController();
  bool isAdmin = false;

  @override
  void initState() {
    super.initState();
    _initAdmin();
  }

  Future<void> _initAdmin() async {
    final admin = await isCurrentUserAdmin();
    if (mounted) setState(() => isAdmin = admin);
  }

  Future<void> postNotice() async {
    final text = notice.text.trim();
    if (text.isEmpty) {
      Fluttertoast.showToast(msg: 'Enter notice text');
      return;
    }
    try {
      await FirebaseFirestore.instance.collection('notices').add({
        'text': text,
        'time': FieldValue.serverTimestamp(),
        'createdBy': FirebaseAuth.instance.currentUser?.uid,
      });
      await showNotification('New Notice', text.split('\n').first);
      notice.clear();
      Fluttertoast.showToast(msg: 'Notice posted');
    } catch (e) {
      Fluttertoast.showToast(msg: 'Post failed: $e');
    }
  }

  @override
  void dispose() {
    notice.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      if (isAdmin)
        Padding(
          padding: const EdgeInsets.all(12),
          child: Column(children: [
            TextField(
              controller: notice,
              maxLines: 5,
              textInputAction: TextInputAction.newline,
              decoration: const InputDecoration(
                labelText: 'Write Notice',
                alignLabelWithHint: true,
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 8),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: postNotice,
                style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, foregroundColor: Colors.white),
                child: const Text('Post Notice'),
              ),
            ),
          ]),
        ),
      Expanded(
        child: StreamBuilder<QuerySnapshot>(
          stream: FirebaseFirestore.instance.collection('notices').orderBy('time', descending: true).snapshots(),
          builder: (context, snap) {
            if (!snap.hasData) return const Center(child: CircularProgressIndicator());
            final docs = snap.data!.docs;
            if (docs.isEmpty) return const Center(child: Text('No notices yet'));
            return ListView.builder(
              itemCount: docs.length,
              itemBuilder: (context, i) {
                final doc = docs[i];
                final data = doc.data() as Map<String, dynamic>;
                final text = (data['text'] ?? '').toString();
                return Card(
                  margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  child: ListTile(
                    title: Text(text, style: const TextStyle(height: 1.4)),
                    trailing: isAdmin
                        ? IconButton(
                            icon: const Icon(Icons.delete),
                            onPressed: () async {
                              await doc.reference.delete();
                              Fluttertoast.showToast(msg: 'Deleted');
                            },
                          )
                        : null,
                  ),
                );
              },
            );
          },
        ),
      ),
    ]);
  }
}

// -------------------- Exam Page --------------------
// Each exam type (Quiz/Assignment/Presentation, Mid, Final) is posted as a separate document.
// Admin can post multi-line text. Each document has 'type' and 'details' fields.
class ExamPage extends StatefulWidget {
  const ExamPage({super.key});
  @override
  State<ExamPage> createState() => _ExamPageState();
}

class _ExamPageState extends State<ExamPage> {
  final quizCtrl = TextEditingController();
  final midCtrl = TextEditingController();
  final finalCtrl = TextEditingController();
  bool isAdmin = false;

  @override
  void initState() {
    super.initState();
    _initAdmin();
  }

  Future<void> _initAdmin() async {
    final admin = await isCurrentUserAdmin();
    if (mounted) setState(() => isAdmin = admin);
  }

  Future<void> postIndividualExam(String type, String text) async {
    final body = text.trim();
    if (body.isEmpty) return;
    try {
      await FirebaseFirestore.instance.collection('exams').add({
        'type': type,
        'details': body,
        'time': FieldValue.serverTimestamp(),
        'createdBy': FirebaseAuth.instance.currentUser?.uid,
      });
      // Send brief notification (first line)
      await showNotification('Exam Update', '$type: ${body.split('\n').first}');
    } catch (e) {
      Fluttertoast.showToast(msg: 'Failed to post $type: $e');
    }
  }

  Future<void> postAll() async {
    if (quizCtrl.text.trim().isEmpty && midCtrl.text.trim().isEmpty && finalCtrl.text.trim().isEmpty) {
      Fluttertoast.showToast(msg: 'Please enter at least one field');
      return;
    }
    if (quizCtrl.text.trim().isNotEmpty) await postIndividualExam('Quiz / Assignment / Presentation', quizCtrl.text);
    if (midCtrl.text.trim().isNotEmpty) await postIndividualExam('Mid Exam', midCtrl.text);
    if (finalCtrl.text.trim().isNotEmpty) await postIndividualExam('Final Exam', finalCtrl.text);

    quizCtrl.clear();
    midCtrl.clear();
    finalCtrl.clear();
    Fluttertoast.showToast(msg: 'Exam info posted');
  }

  Future<void> _editExamDoc(DocumentSnapshot doc) async {
    final data = doc.data() as Map<String, dynamic>;
    final type = (data['type'] ?? '').toString();
    final details = (data['details'] ?? '').toString();
    final editCtrl = TextEditingController(text: details);

    await showDialog(
      context: context,
      builder: (_) => StatefulBuilder(builder: (context, setDialog) {
        return AlertDialog(
          title: Text('Edit: $type'),
          content: Column(mainAxisSize: MainAxisSize.min, children: [
            TextField(controller: editCtrl, maxLines: 8, decoration: const InputDecoration(border: OutlineInputBorder(), labelText: 'Details')),
          ]),
          actions: [
            TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
            ElevatedButton(
              onPressed: () async {
                final newDetails = editCtrl.text.trim();
                await doc.reference.set({
                  'type': type,
                  'details': newDetails,
                  'time': FieldValue.serverTimestamp(),
                  'createdBy': FirebaseAuth.instance.currentUser?.uid,
                });
                Navigator.pop(context);
                Fluttertoast.showToast(msg: 'Updated');
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, foregroundColor: Colors.white),
              child: const Text('Save'),
            ),
          ],
        );
      }),
    );
    editCtrl.dispose();
  }

  @override
  void dispose() {
    quizCtrl.dispose();
    midCtrl.dispose();
    finalCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      if (isAdmin)
        Padding(
          padding: const EdgeInsets.all(12),
          child: Column(children: [
            // Quiz / Assignment / Presentation (multi-line)
            TextField(
              controller: quizCtrl,
              maxLines: 4,
              textInputAction: TextInputAction.newline,
              decoration: const InputDecoration(
                labelText: 'Quiz / Assignment / Presentation',
                border: OutlineInputBorder(),
                alignLabelWithHint: true,
              ),
            ),
            const SizedBox(height: 8),
            // Mid exam
            TextField(
              controller: midCtrl,
              maxLines: 4,
              textInputAction: TextInputAction.newline,
              decoration: const InputDecoration(
                labelText: 'Mid Exam Details',
                border: OutlineInputBorder(),
                alignLabelWithHint: true,
              ),
            ),
            const SizedBox(height: 8),
            // Final exam
            TextField(
              controller: finalCtrl,
              maxLines: 4,
              textInputAction: TextInputAction.newline,
              decoration: const InputDecoration(
                labelText: 'Final Exam Details',
                border: OutlineInputBorder(),
                alignLabelWithHint: true,
              ),
            ),
            const SizedBox(height: 10),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: postAll,
                style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, foregroundColor: Colors.white),
                child: const Text('Post Exam Info (separate entries)'),
              ),
            ),
          ]),
        ),
      Expanded(
        child: StreamBuilder<QuerySnapshot>(
          stream: FirebaseFirestore.instance.collection('exams').orderBy('time', descending: true).snapshots(),
          builder: (context, snap) {
            if (!snap.hasData) return const Center(child: CircularProgressIndicator());
            final docs = snap.data!.docs;
            if (docs.isEmpty) return const Center(child: Text('No exam info yet'));
            return ListView.builder(
              itemCount: docs.length,
              itemBuilder: (context, i) {
                final doc = docs[i];
                final data = doc.data() as Map<String, dynamic>;
                final type = (data['type'] ?? 'Exam').toString();
                final details = (data['details'] ?? '').toString();
                return Card(
                  margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  child: ListTile(
                    title: Text(type, style: const TextStyle(fontWeight: FontWeight.bold)),
                    subtitle: Text(details, style: const TextStyle(height: 1.4)),
                    trailing: isAdmin
                        ? Row(mainAxisSize: MainAxisSize.min, children: [
                            IconButton(icon: const Icon(Icons.edit), onPressed: () => _editExamDoc(doc)),
                            IconButton(icon: const Icon(Icons.delete), onPressed: () async { await doc.reference.delete(); Fluttertoast.showToast(msg: 'Deleted'); }),
                          ])
                        : null,
                  ),
                );
              },
            );
          },
        ),
      ),
    ]);
  }
}

// -------------------- Routine Page --------------------
// Routine stored as document per day: /routines/{day} { data: [ {course,teacher,room}, ... ] }
class RoutinePage extends StatefulWidget {
  const RoutinePage({super.key});
  @override
  State<RoutinePage> createState() => _RoutinePageState();
}

class _RoutinePageState extends State<RoutinePage> {
  String selectedDay = 'Sunday';
  bool isAdmin = false;

  final times = [
    '8:20 - 9:50',
    '9:50 - 11:20',
    '11:20 - 12:50',
    '1:10 - 2:40',
    '2:40 - 4:10',
  ];

  Map<String, List<Map<String, String>>> routineData = {};

  @override
  void initState() {
    super.initState();
    _init();
  }

  Future<void> _init() async {
    final admin = await isCurrentUserAdmin();
    setState(() => isAdmin = admin);
    await loadRoutine();
  }

  Future<void> loadRoutine() async {
    final snap = await FirebaseFirestore.instance.collection('routines').doc(selectedDay).get();
    if (snap.exists) {
      final raw = snap['data'] as List<dynamic>? ?? [];
      routineData[selectedDay] = raw.map((e) => Map<String, String>.from(e as Map)).toList();
    } else {
      routineData[selectedDay] = List.generate(times.length, (_) => {'course': '', 'teacher': '', 'room': ''});
    }
    setState(() {});
  }

  Future<void> saveRoutine() async {
    final dataToSave = routineData[selectedDay] ?? List.generate(times.length, (_) => {'course': '', 'teacher': '', 'room': ''});
    await FirebaseFirestore.instance.collection('routines').doc(selectedDay).set({
      'data': dataToSave,
      'updatedAt': FieldValue.serverTimestamp(),
    });
    Fluttertoast.showToast(msg: 'Routine updated for $selectedDay');
  }

  void _editSlot(int index) {
    final slot = routineData[selectedDay]![index];
    final courseCtrl = TextEditingController(text: slot['course']);
    final teacherCtrl = TextEditingController(text: slot['teacher']);
    final roomCtrl = TextEditingController(text: slot['room']);

    showDialog(
      context: context,
      builder: (_) => StatefulBuilder(builder: (context, setDialog) {
        return AlertDialog(
          title: Text('Edit ${times[index]}'),
          content: Column(mainAxisSize: MainAxisSize.min, children: [
            TextField(controller: courseCtrl, decoration: const InputDecoration(labelText: 'Course Code')),
            TextField(controller: teacherCtrl, decoration: const InputDecoration(labelText: 'Teacher Initial')),
            TextField(controller: roomCtrl, decoration: const InputDecoration(labelText: 'Room')),
          ]),
          actions: [
            TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
            ElevatedButton(
              onPressed: () async {
                routineData[selectedDay]![index] = {
                  'course': courseCtrl.text.trim(),
                  'teacher': teacherCtrl.text.trim(),
                  'room': roomCtrl.text.trim(),
                };
                await saveRoutine(); // auto-save immediately
                setState(() {});
                Navigator.pop(context);
              },
              style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, foregroundColor: Colors.white),
              child: const Text('Save'),
            ),
          ],
        );
      }),
    );
  }

  @override
  Widget build(BuildContext context) {
    final daySlots = routineData[selectedDay] ?? List.generate(times.length, (_) => {'course': '', 'teacher': '', 'room': ''});
    return Padding(
      padding: const EdgeInsets.all(12),
      child: Column(children: [
        Row(children: [
          const Text('Day:', style: TextStyle(fontWeight: FontWeight.bold)),
          const SizedBox(width: 8),
          Expanded(
            child: DropdownButton<String>(
              value: selectedDay,
              isExpanded: true,
              items: const ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
                  .map((d) => DropdownMenuItem(value: d, child: Text(d)))
                  .toList(),
              onChanged: (v) async {
                if (v == null) return;
                setState(() => selectedDay = v);
                await loadRoutine();
              },
            ),
          ),
          const SizedBox(width: 8),
          if (isAdmin)
            ElevatedButton(
              onPressed: saveRoutine,
              style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo, foregroundColor: Colors.white),
              child: const Text('Save'),
            ),
        ]),
        const SizedBox(height: 10),
        Expanded(
          child: ListView.builder(
            itemCount: times.length,
            itemBuilder: (context, i) {
              final slot = daySlots[i];
              return Card(
                margin: const EdgeInsets.symmetric(vertical: 6),
                child: ListTile(
                  title: Text(times[i], style: const TextStyle(fontWeight: FontWeight.bold)),
                  subtitle: Text('Course: ${slot['course']}\nTeacher: ${slot['teacher']}\nRoom: ${slot['room']}', style: const TextStyle(height: 1.3)),
                  trailing: isAdmin ? IconButton(icon: const Icon(Icons.edit), onPressed: () => _editSlot(i)) : null,
                ),
              );
            },
          ),
        ),
      ]),
    );
  }
}
